# .github/workflows/build.yml
name: Merge images and generate PDF files.
permissions: write-all
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Commit to Build branch
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - name: Create Folders
        run: mkdir build && mkdir tmp

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      
      - name: Install Dependencies
        run: python -m pip install pypdf Pillow

      - name: Build
        run: python3 pdf.py

      - name: Push to Build branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build # The branch name where you want to push the assets
          FOLDER: build # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Builds to commit ({sha}) from main: {msg}" # The commit message
